"""Robust parser for raw Boltzmann solver data files (background.dat, pk.dat)."""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np

from dmra._typing import FloatArray
from dmra.cosmology.boltzmann.result import BackgroundHistory
from dmra.cosmology.boltzmann.units import UnitGatekeeper


def parse_class_table(
    file_path: Path | str,
) -> tuple[dict[str, int], FloatArray]:
    """Parse space- or tab-delimited CLASS table file, extracting headers and data.

    Parameters
    ----------
    file_path:
        Path to raw ASCII table file generated by CLASS / AxiCLASS.

    Returns
    -------
    column_indices:
        Mapping from standardized column name to 0-indexed column integer.
    data_matrix:
        2D NumPy array of table values with shape (num_rows, num_columns).
    """
    path = Path(file_path).resolve()
    if not path.exists():
        raise FileNotFoundError(f"Boltzmann data file not found: {path}")

    header_line: str | None = None
    lines: list[str] = []

    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("#"):
                # CLASS header line usually has format: # 1:z 2:conf. time ...
                # or # k (h/Mpc) P (Mpc/h)^3
                if any(kw in stripped.lower() for kw in ("z", "k", "h", "rho", "omega", "time")):
                    header_line = stripped
                continue
            lines.append(stripped)

    if not lines:
        raise ValueError(f"Table file {path.name} contains no numeric data rows")

    data = np.loadtxt(lines, dtype=np.float64)
    if data.ndim == 1:
        data = data.reshape(1, -1)

    column_map: dict[str, int] = {}
    if header_line is not None:
        # Clean leading '#' and split tokens
        cleaned_hdr = header_line.lstrip("#").strip()
        # Handle CLASS enumerated tokens like '1:z  2:H [1/Mpc]  3:conf. time [Mpc]'
        # Split on whitespace followed by digit(s) and colon
        split_parts = [p.strip() for p in re.split(r"(?:\s+|^)\d+:", cleaned_hdr) if p.strip()]
        raw_tokens = split_parts or cleaned_hdr.split()

        for idx, token in enumerate(raw_tokens):
            norm_name = re.sub(r"\[.*?\]|\(.*?\)", "", token).strip().lower().replace(" ", "_")
            if norm_name:
                column_map[norm_name] = idx

    return column_map, data


def parse_class_power_spectrum(
    pk_path: Path | str,
    h: float,
    _redshift: float = 0.0,
) -> tuple[FloatArray, FloatArray]:
    """Parse CLASS pk.dat and convert from raw Mpc units to DMRA h-scaled units."""
    path = Path(pk_path).resolve()
    with open(path, encoding="utf-8", errors="replace") as f:
        first_few = [f.readline() for _ in range(10)]
    header_text = " ".join(first_few).lower()
    _col_map, data = parse_class_table(path)
    k = data[:, 0]
    pk = data[:, 1]
    if "h/mpc" in header_text and "mpc/h" in header_text:
        # File is already in CLASS default h-scaled units (k [h/Mpc], P [(Mpc/h)^3])
        return k, pk
    if "1/mpc" in header_text and "mpc^3" in header_text:
        return UnitGatekeeper.class_to_project_power(k, pk, h)
    raise ValueError("power table must explicitly declare both k and P units")


def extract_solver_sigma8(stdout_text: str) -> float | None:
    """Extract solver-reported sigma8 value from CLASS/AxiCLASS execution stdout."""
    match = re.search(
        r"sigma8\s*=\s*([0-9.+\-]+(?:[eE][+\-]?\d+)?)\s+for total matter", stdout_text
    )
    if match:
        return float(match.group(1))
    return None


def build_background_history_from_table(
    table_data: FloatArray,
    col_map: dict[str, int],
    _h: float = 0.7,
) -> BackgroundHistory:
    """Construct a validated BackgroundHistory instance from a parsed background table."""

    def find_col(*candidates: str) -> int:
        for cand in candidates:
            for k, idx in col_map.items():
                if cand == k:
                    return idx
        raise KeyError(f"Could not locate column matching any of {candidates} in {col_map}")

    def get_col_opt(*candidates: str) -> int | None:
        for cand in candidates:
            for k, idx in col_map.items():
                if cand == k:
                    return idx
        return None

    idx_z = find_col("z")
    idx_h = find_col("h")

    z = table_data[:, idx_z]
    a = 1.0 / (1.0 + z)

    # CLASS H is physical H [1/Mpc]
    raw_h = table_data[:, idx_h]
    h_kms_mpc = UnitGatekeeper.hubble_inv_mpc_to_kms_mpc(raw_h)

    idx_crit = get_col_opt("rho_crit")
    rho_crit = table_data[:, idx_crit] if idx_crit is not None else None

    # Matter density fraction
    idx_om = get_col_opt("omega_m")
    if idx_om is not None:
        om = table_data[:, idx_om]
    elif rho_crit is not None and get_col_opt("rho_cdm") is not None:
        idx_cdm = find_col("rho_cdm")
        idx_b = get_col_opt("rho_b")
        rho_m = table_data[:, idx_cdm] + (table_data[:, idx_b] if idx_b is not None else 0.0)
        om = rho_m / rho_crit
    else:
        raise ValueError("background lacks matter densities; refusing to invent a cosmology")

    # Radiation density fraction
    idx_or = get_col_opt("omega_r", "omega_rad")
    if idx_or is not None:
        orad = table_data[:, idx_or]
    elif rho_crit is not None and get_col_opt("rho_g") is not None:
        idx_g = find_col("rho_g")
        idx_ur = get_col_opt("rho_ur")
        rho_r = table_data[:, idx_g] + (table_data[:, idx_ur] if idx_ur is not None else 0.0)
        orad = rho_r / rho_crit
    else:
        raise ValueError("background lacks radiation densities")

    # EDE / scalar field density fraction
    idx_op = get_col_opt("omega_ede", "omega_scf", "omega_fld", "omega_phi")
    if idx_op is not None:
        op = table_data[:, idx_op]
    elif rho_crit is not None and get_col_opt("rho_scf", "rho_ede", "rho_phi") is not None:
        idx_scf = find_col("rho_scf", "rho_ede", "rho_phi")
        op = table_data[:, idx_scf] / rho_crit
    else:
        op = np.zeros_like(z)

    # Cosmological constant fraction
    idx_ol = get_col_opt("omega_lambda")
    if idx_ol is not None:
        ol = table_data[:, idx_ol]
    elif rho_crit is not None and get_col_opt("rho_lambda") is not None:
        idx_lambda = find_col("rho_lambda")
        ol = table_data[:, idx_lambda] / rho_crit
    else:
        ol = np.zeros_like(z)

    # CLASS_EDE rho_scf includes a constant potential term. Its source defines
    # rho_CLASS = (kinetic + V)/3. Measure the constant at the final epoch to
    # avoid subtracting nearly equal, large early-time potentials.
    if "v_e_scf" in col_map and "v_scf" in col_map and rho_crit is not None:
        present = int(np.argmin(z))
        rho_cc = (
            table_data[present, col_map["v_scf"]] - table_data[present, col_map["v_e_scf"]]
        ) / 3.0
        op = op - rho_cc / rho_crit
        ol = ol + rho_cc / rho_crit

    return BackgroundHistory(
        z=z,
        a=a,
        H_z=h_kms_mpc,
        omega_m=om,
        omega_r=orad,
        omega_lambda=ol,
        omega_phi=op,
    )
